# Generated by Django 5.1.1 on 2024-11-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_item_created_at_item_nb_sales_delete_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.TextField(default='https://mac-center.com.pr/cdn/shop/files/iPhone_16_Pro_Natural_Titanium_PDP_Image_Position_1__en-US.jpg?v=1726226576'),
            preserve_default=False,
        ),
    ]
