# Generated by Django 5.1.1 on 2024-11-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='phone', max_length=255),
            preserve_default=False,
        ),
    ]
